version: '3'

services:
  api:
    build: .
    container_name: gestao-api
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - '8000:8000'
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
